apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ledger-dev
resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-ingress.yaml
images:
  - name: ghcr.io/tinoosan/ledger
    newTag: dev

