apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ledger
          imagePullPolicy: Always
          # (only dev pulls each time; prod will pin digests later)
          envFrom:
            - configMapRef:
                name: ledger-config
            - secretRef:
                name: ledger-secrets
