apiVersion: v1
kind: Secret
metadata:
  name: ledger-secrets
type: Opaque
stringData:
  - DATABASE_URL: postgresql://user:pass@postgresql.default.svc.cluster.local:5432/ledger?sslmode=disable
  - JWT_HS256_SECRET: "dev-secret-change-me"


