apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tools
  namespace: tools
spec:
  ingressClassName: nginx
  rules:
  - host: tools.jamaguchi.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: it-tools
            port:
              name: http
