apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 5m
  path: ./infra/monitoring
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

