# flux-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-kustomization
  namespace: flux-system
spec:
  interval: 5m
  path: ./      
  prune: true    
  wait: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system

