apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tools
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/it-tools/base
  prune: true
  wait: true
  dependsOn:
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
