apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app: plex
spec:
  type: NodePort
  selector:
    app: plex
  ports:
    - name: plex
      port: 32400
      targetPort: 32400   
      nodePort: 32400     

