apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 10m
  chart:
    spec:
      chart: keycloak
      version: 25.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: keycloak-common-values
      valuesKey: values.common.yaml
