apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: keycloak-common-values
    files:
      - values.common.yaml
generatorOptions:
  disableNameSuffixHash: true
