replicas: 1
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    memory: 1Gi

proxy: edge
httpRelativePath: "/"

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  # host & tls injected by overlay

persistence:
  enabled: true
  size: 5Gi
  # storageClass injected by overlay if needed

# Choose DB mode via overlays:
postgresql:
  enabled: false     # external DB by default; override to true if you want bundled PG

# External DB placeholders (overlays supply real values or existingSecret)
externalDatabase:
  host: ""           # e.g., postgres-keycloak
  port: 5432
  user: ""
  password: ""       # or use existingSecret
  database: ""
