apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  template:
    spec:
      containers:
        - name: metabase
          env:
            - name: MB_DB_TYPE
              value: postgres
            - name: MB_DB_HOST
              value: postgres
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_DBNAME
              value: metabase
            - name: MB_DB_USER
              value: metabase
            - name: MB_LOAD_FROM_H2
              value: "1"
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_PASSWORD
