apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    configmap.revisions: "4"
  name: plex-configmap
  namespace: default
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Etc/UTC"
  VERSION: "docker"
  PLEX_CLAIM: "claim-5exsQ_vGcQXeFz3sxxxS"

