apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plex
  name: plex
  namespace: default
spec:
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: lscr.io/linuxserver/plex:latest
        env:
          - name: PUID
            valueFrom:
              configMapKeyRef:
                name: plex-configmap
                key: PUID
          - name: PGID
            valueFrom:
              configMapKeyRef:
                name: plex-configmap
                key: PGID
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: plex-configmap
                key: TZ
          - name: VERSION
            valueFrom:
              configMapKeyRef:
                name: plex-configmap
                key: VERSION
        volumeMounts:
          - name: plex-volume
            mountPath: /media
          - name: plex-config
            mountPath: /config
          - name: dri-device
            mountPath: /dev/dri
            readOnly: true
        securityContext:
          privileged: true
        ports:
        - containerPort: 32400
      volumes:
       - name: plex-volume
         hostPath:
          path: /mnt/gdrive/Videos
          type: Directory
       - name: dri-device
         hostPath:
          path: /dev/dri
          type: Directory     
       - name: plex-config
         hostPath:
          path: /srv
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: default
spec:
  selector:
    app: plex
  ports:
    - protocol: TCP
      port: 32400
      targetPort: 32400
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  spec:
  ingressClassName: nginx
  rules:
  - host: plex.jamaguchi.net
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: plex
            port:
              number: 32400

