apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: default
  labels:
    app: it-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-tools
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
      - name: it-tools
        image: corentinth/it-tools:nightly
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools
  namespace: default
spec:
  selector:
    app: it-tools
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

