apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        homelab.dev/rollout-nonce: "2025-10-01-01"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command: ["sh","-c","mkdir -p /home/node/.n8n && chown -R 1000:1000 /home/node/.n8n"]
          volumeMounts:
            - name: data
              mountPath: /home/node/.n8n
      containers:
        - name: n8n
          imagePullPolicy: Always
