apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  # Secret is managed manually out-of-band
