apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  template:
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 127.0.0.1
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
      containers:
        - name: gluetun
          image: qmcgaw/gluetun
          imagePullPolicy: IfNotPresent
          securityContext:
            # Override pod defaults to run Gluetun as root with NET_ADMIN
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: true
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: TZ
              value: Europe/London
            - name: VPN_SERVICE_PROVIDER
              value: nordvpn
            - name: VPN_TYPE
              value: openvpn
            - name: FIREWALL_INPUT_PORTS
              value: "5678"
            - name: HEALTH_VPN
              value: "on"
          envFrom:
            - secretRef:
                name: vpn-secret
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
