apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
          envFrom:
              - secretRef:
                  name: secret.yaml
              - configMapRef: { name: keycloak-db-config }
          volumeMounts:
            - name: keycloak
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
  volumeClaimTemplates:
    - metadata:
        name: keycloak
      spec:
        accessModes: ["ReadWriteOnce"]
        resources: { requests: {storage: 2Gi} }
