apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        imagePullPolicy: IfNotPresent
        args:
            - start-dev
            - http-enabled=true
        ports:
          - name: http
            containerPort: 8080
        envFrom:
            - configMapRef:
                name: keycloak-config
            - secretRef:
                name: keycloak-secrets
        readinessProbe:
                httpGet: { path: /health/ready, port: 8080 }
                initialDelaySeconds: 25
                periodSeconds: 10
        livenessProbe:
          httpGet: { path: /health/live, port: 8080 }
          initialDelaySeconds: 40
          periodSeconds: 15
        resources:
          requests: { cpu: 250m, memory: 512Mi }
          limits:   { memory: 1Gi }
