apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - namespace.yaml
  - deployment.yaml
  - configmap.yaml
  - secrets.yaml
  - service.yaml
  - ingress.yaml
