apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
stringData:
    KEYCLOAK_ADMIN: admin
    KEYCLOAK_ADMIN_PASSWORD: admin
    KC_DB: postgres
    KC_DB_URL: <DBURL>
    KC_DB_USERNAME: <DBUSERNAME>
    KC_DB_PASSWORD: <DBPASSWORD>

