apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  template:
    spec:
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
      containers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop: ["ALL"]
              add: ["NET_ADMIN"]
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: TZ
              value: Europe/London
            - name: VPN_SERVICE_PROVIDER
              value: nordvpn
            - name: VPN_TYPE
              value: openvpn
            - name: SERVER_COUNTRIES
              value: Netherlands
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: DOT
              value: "off"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
            - name: FIREWALL_INPUT_PORTS
              value: "9091,51413"
            - name: HEALTH_VPN
              value: "on"
          envFrom:
            - secretRef:
                name: vpn-secret
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
