apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ledger-dev
resources:
  - ../../base
  - secret-app-creds.yaml
configMapGenerator:
  - name: pg-init
    files:
      - 00-roles.sh=init/00-roles.sh
      - 01-schema.sql=init/01-schema.sql
patchesStrategicMerge:
  - patch-statefulset.yaml
