apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ledger-dev
resources:
  - ../../base
  - secret-app-creds.yaml
configMapGenerator:
  - name: ledger-pg-init
    files:
      - init/0001_init.sql
patches:
  - path: patch-statefulset.yaml
