apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ledger-dev
resources:
  - ../../base
  - secret-app-creds.yaml
configMapGenerator:
  - name: pg-init
    files:
      - 00-schema.sql=0001_init.sql
patchesStrategicMerge:
  - path: patch-statefulset.yaml
