apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - servicemonitor.yaml
images:
  - name: ghcr.io/tinoosan/torrus
    newTag: dev   # placeholder; overlays will override
