apiVersion: apps/v1
kind: Deployment
metadata:
  name: aria2
spec:
  template:
    metadata:
      annotations:
        homelab.dev/rollout-nonce: "2025-10-27-01"
    spec:
      nodeSelector:
        kubernetes.io/hostname: mugiwara

      containers:
        - name: aria2
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          env:
            - name: PUID
              value: "65532"
            - name: PGID
              value: "65532"
          volumeMounts:
            - name: downloads-tv
              mountPath: /downloads/tv
            - name: downloads-movies
              mountPath: /downloads/movies

      volumes:
        - name: downloads-tv
          hostPath:
            path: /media/test/tv
            type: DirectoryOrCreate
        - name: downloads-movies
          hostPath:
            path: /media/test/movies
            type: DirectoryOrCreate
