apiVersion: apps/v1
kind: Deployment
metadata:
  name: aria2
spec:
  template:
    metadata:
      annotations:
        homelab.dev/rollout-nonce: "2025-10-27-02"
    spec:
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
      nodeSelector:
        kubernetes.io/hostname: mugiwara

      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command:
            - sh
            - -c
            - >-
              mkdir -p /downloads/tv /downloads/movies &&
              chown -R 65532:65532 /downloads/tv /downloads/movies &&
              chmod -R 775 /downloads/tv /downloads/movies
          volumeMounts:
            - name: downloads-tv
              mountPath: /downloads/tv
            - name: downloads-movies
              mountPath: /downloads/movies

      containers:
        - name: aria2
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
          env:
            - name: PUID
              value: "65532"
            - name: PGID
              value: "65532"
          volumeMounts:
            - name: downloads-tv
              mountPath: /downloads/tv
            - name: downloads-movies
              mountPath: /downloads/movies

      volumes:
        - name: downloads-tv
          hostPath:
            path: /media/test/tv
            type: DirectoryOrCreate
        - name: downloads-movies
          hostPath:
            path: /media/test/movies
            type: DirectoryOrCreate
