apiVersion: apps/v1
kind: Deployment
metadata:
  name: aria2
spec:
  template:
    metadata:
      annotations:
        rollout/nonce: "2025-09-07T15:30:34Z"
    spec:
      nodeSelector:
        kubernetes.io/hostname: mugiwara

      containers:
        - name: aria2
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
          volumeMounts:
            - name: aria2-data
              mountPath: /data

      volumes:
        - name: aria2-data
          hostPath:
            path: /media/test
            type: Directory
