apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: torrus-dev
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: APP_DB
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: APP_DB
            - name: APP_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: APP_USER
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: APP_PASSWORD
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_PASSWORD
      volumes:
      - name: init-scripts
        configMap:
          name: pg-init
          defaultMode: 0755