apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: torrus-dev
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: APP_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: APP_DB
            - name: APP_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: APP_USER
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: APP_PASSWORD
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: POSTGRES_PASSWORD
          volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
            subPath: pgdata
          - name: init-scripts
            mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-scripts
        configMap:
          name: pg-init
          defaultMode: 0755