apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: APP_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: APP_DB
            - name: APP_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: APP_USER
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: APP_PASSWORD
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: POSTGRES_PASSWORD
      volumes:
      - name: init-scripts
        configMap:
          name: pg-init-scripts
          defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
