apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
spec:
  ingressClassName: nginx
  rules:
  - host: n8n.jamaguchi.xyz   # patched per env if needed
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: n8n
              port:
                name: http
