apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  template:
    spec:
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
      containers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun@sha256:75d4573f6816bc08651c436845b4b6c7abeddf9a5f4d908880d255aa2696ed65
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop: []
              add: ["NET_ADMIN", "NET_RAW"]
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: TZ
              value: Europe/London
            - name: VPN_SERVICE_PROVIDER
              value: nordvpn
            - name: VPN_TYPE
              value: openvpn
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: DOT
              value: "off"
            - name: BLOCK_MALICIOUS
              value: "off"
            - name: BLOCK_SURVEILLANCE
              value: "off"
            - name: BLOCK_ADS
              value: "off"
            - name: DNS_ADDRESS
              value: "1.1.1.1"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
            - name: FIREWALL_INPUT_PORTS
              value: "7878"
            - name: HEALTH_VPN
              value: "on"
          envFrom:
            - secretRef:
                name: vpn-secret
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
