apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: networking
data:
  config.yaml: |
    # Cloudflared ingress mappings. Public hostnames → cluster ingress
    ingress:
      # Apps with Ingress
      - hostname: n8n.jamaguchi.xyz
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: ledger.dev.jamaguchi.xyz
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: pgadmin.jamaguchi.xyz
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: keycloak.jamaguchi.xyz
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: grafana.jamaguchi.xyz
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      # Default 404 catch-all
      - service: http_status:404
